// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times=Integer.parseInt(args[0]);
		int count1 =0; 
		int count2 =0;
		double random;
		double ratio;
		for(int i = 0 ; i < times ; i++ ){
			random=Math.random();
			if( random > 0.5 )
				count1++;
			else
				count2++;
		}
		System.out.println("> 0.5: " + count1 + " times");
	    System.out.println("<= 0.5: " + count2 + " times");
		if( count1 != 0 && count2!=0){
			if (count1> count2){
				ratio =  (double) count2 / count1;
			} else{
				ratio =  (double) count1 / count2;
			}
			System.out.println("Ratio: " + ratio );
		}
	}
}
